spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/idss?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: idss-hikari
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1