server:
  port: 8082
spring:
  application:
    name: fensibox-cms
  profiles:
    active: prod
  redis:
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 6
        max-wait: -1ms
    timeout: 60s